package com.shannontheoret.duel;

public enum GameStep {
    SETUP,
    WONDER_SELECTION,
    PLAY_CARD,
    CHOOSE_PROGRESS_TOKEN,
    DESTROY_GREY,
    DESTROY_BROWN,
    CHOOSE_PROGRESS_TOKEN_FROM_DISCARD,
    CONSTRUCT_FROM_DISCARD,
    GAME_END;
}
