package com.shannontheoret.duel;

public enum PlayerMove {
    SELECT_WONDER,
    CONSTRUCT_WONDER,
    CONSTRUCT_BUILDING,
    DISCARD,
    CHOOSE_PROGRESS_TOKEN,
    CHOOSE_PROGRESS_TOKEN_FROM_DISCARD,
    DESTROY_CARD,
    CONSTRUCT_FROM_DISCARD
}
