options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/hale-wind-461813-i3/duel', '-f', 'duel/Dockerfile', 'duel']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - duel
      - --image=gcr.io/hale-wind-461813-i3/duel
      - --region=northamerica-northeast2
      - --platform=managed
      - --allow-unauthenticated
      - --clear-env-vars=SPRING_DATASOURCE_URL,SPRING_DATASOURCE_USERNAME,SPRING_DATASOURCE_PASSWORD,OPENAI_API_KEY
      - --set-secrets=SPRING_DATASOURCE_URL=SPRING_DATASOURCE_URL:latest, SPRING_DATASOURCE_USERNAME=SPRING_DATASOURCE_USERNAME:latest, SPRING_DATASOURCE_PASSWORD=SPRING_DATASOURCE_PASSWORD:latest, OPENAI_API_KEY=OPENAI_API_KEY:latest
      - --port=8081

images:
  - 'gcr.io/hale-wind-461813-i3/duel'